services:
  web:
    build: .
    command: python UniChoose/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - 5433
    ports:
      - 5433:5433
    command: -p 5433

volumes:
  postgres_data: