# Generated by Django 3.2.16 on 2022-12-10 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(10.0)], verbose_name='average rating')),
                ('rating_count', models.PositiveSmallIntegerField(verbose_name='rating count')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
            ],
            options={
                'verbose_name': 'university',
                'verbose_name_plural': 'universities',
            },
        ),
    ]
