# Generated by Django 3.2.16 on 2022-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
