# Generated by Django 3.2.16 on 2022-12-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='new_region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='universities',
                to='universities.region'),
        ),
    ]
