# Generated by Django 3.2.16 on 2022-12-12 12:40

from django.db import migrations


def change_new_region(apps, schema_editor):
    universities = apps.get_model('universities', 'University')
    regions = apps.get_model('universities', 'Region')

    for uni in universities.objects.all():
        reg = uni.region
        uni.new_region = regions.objects.get(name=reg)

        uni.save()


class Migration(migrations.Migration):
    dependencies = [
        ('universities', '0004_university_new_region'),
    ]

    operations = [
        migrations.RunPython(change_new_region),
    ]
