# Generated by Django 3.2.16 on 2022-12-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_remove_university_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='new_region',
            new_name='region',
        ),
    ]
