# Generated by Django 3.2.16 on 2022-12-12 13:42

from django.db import migrations


def swap_latitude_longitude(apps, schema_editor):
    regions = apps.get_model('universities', 'Region')

    for region in regions.objects.all():
        region.latitude, region.longitude = region.longitude, region.latitude

        region.save()


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_rename_new_region_university_region'),
    ]

    operations = [
        migrations.RunPython(swap_latitude_longitude),
    ]
