# Generated by Django 3.2.16 on 2022-12-10 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_delete_accountdepartmentrelations'),
        ('universities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='liked_dpts',
            field=models.ManyToManyField(to='departments.Department', verbose_name='liked departments'),
        ),
        migrations.AddField(
            model_name='account',
            name='liked_unis',
            field=models.ManyToManyField(to='universities.University', verbose_name='liked universities'),
        ),
        migrations.CreateModel(
            name='AccountDepartmentRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveSmallIntegerField(verbose_name='relation strength')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='departments.department')),
            ],
        ),
    ]
