# Generated by Django 3.2.16 on 2022-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221211_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ege_marks',
            field=models.JSONField(null=True, verbose_name='ege marks'),
        ),
    ]
