# Generated by Django 3.2.16 on 2022-12-12 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_alter_weighteddepartment_department'),
        ('users', '0003_auto_20221211_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdepartmentrelations',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='relations',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountdepartmentrelations',
            name='department',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='relations',
                to='departments.department'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='subjects',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
