# Generated by Django 3.2.16 on 2022-12-12 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('entry_score', models.IntegerField(blank=True, null=True)),
                ('vuz_rating',
                 models.DecimalField(
                     blank=True,
                     decimal_places=1,
                     max_digits=3,
                     null=True,
                     validators=[
                         django.core.validators.MaxValueValidator(10.0)
                     ],
                     verbose_name='average rating')),
                ('edu_level', models.IntegerField(blank=True, null=True)),
                ('profile', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='accountdepartmentrelations',
            name='strength',
            field=models.SmallIntegerField(verbose_name='relation strength'),
        ),
        migrations.AddField(
            model_name='account',
            name='preference',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user',
                to='users.preference'),
        ),
    ]
