# Generated by Django 3.2.16 on 2022-12-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221212_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='liked_dpts',
        ),
        migrations.RemoveField(
            model_name='account',
            name='liked_unis',
        ),
    ]
