# Generated by Django 3.2.16 on 2022-12-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221220_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='edu_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
