# Generated by Django 3.2.16 on 2022-12-22 13:17

import django.db.models.deletion
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_alter_region_name'),
        ('users', '0009_alter_preference_edu_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_distance',
            field=models.IntegerField(
                default=1000, validators=[users.validators.validate_distance]),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='universities.region',
                validators=[users.validators.validate_region]),
        ),
    ]
