# Generated by Django 3.2.16 on 2022-12-22 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_alter_region_name'),
        ('users', '0010_auto_20221222_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_distance',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='users',
                to='universities.region'),
        ),
    ]
