# Generated by Django 3.2.16 on 2022-12-10 17:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import departments.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(max_length=200,
                                          verbose_name='name')),
                ('profile', models.TextField(verbose_name='profile')),
                ('profile_class',
                 models.CharField(max_length=20,
                                  validators=[
                                      departments.validators.
                                      validate_department_classification_format
                                  ],
                                  verbose_name='profile class')),
                ('entry_score',
                 models.PositiveSmallIntegerField(
                     validators=[
                         django.core.validators.MaxValueValidator(300)
                     ],
                     verbose_name='minimal entry exam score')),
                ('edu_level',
                 models.PositiveSmallIntegerField(
                     verbose_name='education level')),
                ('ege_subjects',
                 models.JSONField(verbose_name='required_ege_subjects')),
                ('university',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='university',
                                   to='universities.university')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountDepartmentRelations',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('strength',
                 models.PositiveSmallIntegerField(
                     verbose_name='relation strength')),
                ('account',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='account',
                     to=settings.AUTH_USER_MODEL)),
                ('department',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='department',
                     to='departments.department')),
            ],
        ),
    ]
