# Generated by Django 3.2.16 on 2022-12-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDepartmentRelations',
        ),
    ]
