# Generated by Django 3.2.16 on 2022-12-12 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20221212_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighteddepartment',
            name='vuz_rating',
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[django.core.validators.MaxValueValidator(10.0)],
                verbose_name='average rating'),
        ),
    ]
