# Generated by Django 3.2.16 on 2022-12-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_auto_20221212_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighteddepartment',
            name='department',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='weighted',
                to='departments.department'),
        ),
    ]
