# Generated by Django 3.2.16 on 2022-12-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_auto_20221212_1642'),
        ('departments', '0009_alter_weighteddepartment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='departments',
                to='universities.university'),
        ),
    ]
