# Generated by Django 3.2.16 on 2022-12-12 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_alter_department_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighteddepartment',
            name='edu_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighteddepartment',
            name='entry_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighteddepartment',
            name='profile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weighteddepartment',
            name='vuz_rating',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[django.core.validators.MaxValueValidator(10.0)],
                verbose_name='average rating'),
        ),
    ]
