# Generated by Django 3.2.16 on 2022-12-13 13:16

from django.db import migrations


def change_subjects(apps, schema_editor):
    departments = apps.get_model('departments', 'Department')

    for department in departments.objects.all():
        subjects = department.ege_subjects
        for j, i in enumerate(subjects):
            if 'или' in i:
                subjects[j] = i.split('или')
                subjects[j] = [k.strip() for k in subjects[j]]
        department.ege_subjects = subjects
        department.save()


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0011_auto_20221212_2025'),
    ]

    operations = [
        migrations.RunPython(change_subjects),
    ]
