# Generated by Django 3.2.16 on 2022-12-13 13:16
from threading import Thread

from django.db import migrations


def f(departments, i):
    for department in departments.objects.all()[i:i + 500]:
        subjects = department.ege_subjects
        for j, i in enumerate(subjects):
            if 'или' in i:
                subjects[j] = i.split('или')
                subjects[j] = [k.strip() for k in subjects[j]]
                if 'Внутренний экзамен' in subjects[j]:
                    subjects[j].remove('Внутренний экзамен')

        if 'Внутренний экзамен' in subjects:
            subjects.remove('Внутренний экзамен')

        department.ege_subjects = subjects
        department.save()


def change_subjects(apps, schema_editor):
    departments = apps.get_model('departments', 'Department')

    for i in range(0, 17000, 500):
        th = Thread(target=f, args=[departments, i])
        th.start()


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0011_auto_20221212_2025'),
    ]

    operations = [
        migrations.RunPython(change_subjects),
    ]
