# Generated by Django 3.2.16 on 2022-12-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_auto_20221213_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighteddepartment',
            name='edu_level',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
